name: Code quality – RubyCritic

on:
  push:
  pull_request:

jobs:
  rubycritic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"

      - name: Run RubyCritic
        uses: ptuchster/rubycritic-action@main
        with:
          min_score_treshold: 1
          workdir: lib
